{
  imports = [
    ./alacritty.nix
    ./atuin.nix
    ./direnv.nix
    ./feh.nix
    ./fish.nix
    ./git.nix
    ./google-chrome.nix
    ./hyprland.nix
    ./keychain.nix
    ./neovim
    ./pulsemixer.nix
    ./ssh.nix
    ./starship.nix
    ./swaylock.nix
    ./vifm.nix
    ./zathura.nix
    ./zoxide.nix
  ];
}
